import { sanitizeText } from "./sanitizer.ts";

function getSafeFilename(name: string, ext: string): string {
  const safeName = name.toLowerCase().replace(/[^a-z0-9_-]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "") || "project";
  return `${safeName}-documentation.${ext}`;
}

export async function exportReadme(projectId: string): Promise<{ filename: string; content: string }> {
  const { prisma } = await import("../db/prisma.ts");
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      documentations: {
        include: {
          sections: true,
        },
      },
    },
  });

  if (!project) {
    throw new Error(`Project '${projectId}' not found.`);
  }

  const doc = project.documentations[0];
  if (!doc || doc.sections.length === 0) {
    const emptyContent = `# ${project.name}\n\n> Generated by DocuForge AI Engine v${project.docVersion || "1.0.0"}\n\n*No technical documentation has been generated for this repository yet. Click "Generate All" in the project workspace to create documentation.*`;
    return {
      filename: "README.md",
      content: emptyContent,
    };
  }

  const readmeSection = doc.sections.find((s) => s.key === "readme");
  const overviewSection = doc.sections.find((s) => s.key === "overview");

  let content = readmeSection?.content || overviewSection?.content;

  if (!content) {
    content = doc.sections
      .sort((a, b) => a.order - b.order)
      .map((s) => `## ${s.title}\n\n${s.content}`)
      .join("\n\n---\n\n");
  }

  const header = `# ${project.name}\n\n> Generated by DocuForge AI Engine v${project.docVersion || "1.0.0"}\n\n`;
  const sanitized = sanitizeText(header + content);

  return {
    filename: "README.md",
    content: sanitized,
  };
}

/**
 * Pure TypeScript CRC-32 calculator for ZIP file generation
 */
function crc32(buffer: Buffer): number {
  let crc = 0xffffffff;
  for (let i = 0; i < buffer.length; i++) {
    const byte = buffer[i];
    crc ^= byte;
    for (let j = 0; j < 8; j++) {
      if (crc & 1) {
        crc = (crc >>> 1) ^ 0xedb88320;
      } else {
        crc = crc >>> 1;
      }
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

/**
 * Pure TypeScript ZIP Archive Buffer Creator (No external binary dependencies)
 */
export function createZipBuffer(files: Array<{ filename: string; content: string }>): Buffer {
  const localHeaders: Buffer[] = [];
  const centralDirs: Buffer[] = [];
  let offset = 0;

  for (const file of files) {
    const filenameBuf = Buffer.from(file.filename, "utf8");
    const contentBuf = Buffer.from(file.content, "utf8");
    const fileCrc = crc32(contentBuf);
    const uncompressedSize = contentBuf.length;

    // Local File Header (30 bytes + filename length + content length)
    const localHeader = Buffer.alloc(30 + filenameBuf.length);
    localHeader.writeUInt32LE(0x04034b50, 0); // Local header signature
    localHeader.writeUInt16LE(20, 4); // Version needed (2.0)
    localHeader.writeUInt16LE(0, 6); // General bit flag
    localHeader.writeUInt16LE(0, 8); // Compression method (0 = Store)
    localHeader.writeUInt16LE(0, 10); // Last mod time
    localHeader.writeUInt16LE(0, 12); // Last mod date
    localHeader.writeUInt32LE(fileCrc, 14); // CRC-32
    localHeader.writeUInt32LE(uncompressedSize, 18); // Compressed size
    localHeader.writeUInt32LE(uncompressedSize, 22); // Uncompressed size
    localHeader.writeUInt16LE(filenameBuf.length, 26); // Filename length
    localHeader.writeUInt16LE(0, 28); // Extra field length
    filenameBuf.copy(localHeader, 30);

    localHeaders.push(localHeader);
    localHeaders.push(contentBuf);

    // Central Directory Header (46 bytes + filename length)
    const centralDir = Buffer.alloc(46 + filenameBuf.length);
    centralDir.writeUInt32LE(0x02014b50, 0); // Central directory signature
    centralDir.writeUInt16LE(20, 4); // Version made by
    centralDir.writeUInt16LE(20, 6); // Version needed
    centralDir.writeUInt16LE(0, 8); // General bit flag
    centralDir.writeUInt16LE(0, 10); // Compression method
    centralDir.writeUInt16LE(0, 12); // Last mod time
    centralDir.writeUInt16LE(0, 14); // Last mod date
    centralDir.writeUInt32LE(fileCrc, 16); // CRC-32
    centralDir.writeUInt32LE(uncompressedSize, 20); // Compressed size
    centralDir.writeUInt32LE(uncompressedSize, 24); // Uncompressed size
    centralDir.writeUInt16LE(filenameBuf.length, 28); // Filename length
    centralDir.writeUInt16LE(0, 30); // Extra field length
    centralDir.writeUInt16LE(0, 32); // File comment length
    centralDir.writeUInt16LE(0, 34); // Disk number start
    centralDir.writeUInt16LE(0, 36); // Internal file attributes
    centralDir.writeUInt32LE(0, 38); // External file attributes
    centralDir.writeUInt32LE(offset, 42); // Relative offset of local header
    filenameBuf.copy(centralDir, 46);

    centralDirs.push(centralDir);
    offset += localHeader.length + contentBuf.length;
  }

  const centralDirStartOffset = offset;
  let centralDirSize = 0;
  for (const cd of centralDirs) {
    centralDirSize += cd.length;
  }

  // End of Central Directory Record (22 bytes)
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0); // EOCD signature
  eocd.writeUInt16LE(0, 4); // Number of this disk
  eocd.writeUInt16LE(0, 6); // Disk where central directory starts
  eocd.writeUInt16LE(files.length, 8); // Number of central directory records on this disk
  eocd.writeUInt16LE(files.length, 10); // Total number of central directory records
  eocd.writeUInt32LE(centralDirSize, 12); // Size of central directory
  eocd.writeUInt32LE(centralDirStartOffset, 16); // Offset of start of central directory
  eocd.writeUInt16LE(0, 20); // Comment length

  return Buffer.concat([...localHeaders, ...centralDirs, eocd]);
}

export async function exportZipBundle(projectId: string): Promise<{ filename: string; buffer: Buffer }> {
  const { prisma } = await import("../db/prisma.ts");
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      documentations: {
        include: {
          sections: true,
        },
      },
    },
  });

  if (!project) {
    throw new Error(`Project '${projectId}' not found.`);
  }

  const files: Array<{ filename: string; content: string }> = [];
  const doc = project.documentations[0];

  if (!doc || doc.sections.length === 0) {
    files.push({
      filename: "README.md",
      content: sanitizeText(`# ${project.name} Documentation\n\nNo technical documentation generated yet.`),
    });
  } else {
    const sortedSections = doc.sections.sort((a, b) => a.order - b.order);

    const readmeSec = sortedSections.find((s) => s.key === "readme");
    if (readmeSec) {
      files.push({
        filename: "README.md",
        content: sanitizeText(readmeSec.content),
      });
    } else {
      files.push({
        filename: "README.md",
        content: sanitizeText(`# ${project.name} Documentation\n\nGenerated by DocuForge AI`),
      });
    }

    sortedSections.forEach((sec, idx) => {
      const paddedIndex = String(idx + 1).padStart(2, "0");
      const safeKey = sec.key.replace(/_/g, "-");
      files.push({
        filename: `docs/${paddedIndex}-${safeKey}.md`,
        content: sanitizeText(`# ${sec.title}\n\n${sec.content}`),
      });
    });
  }

  const zipBuffer = createZipBuffer(files);
  return {
    filename: getSafeFilename(project.name, "zip"),
    buffer: zipBuffer,
  };
}

/**
 * Pure TypeScript PDF-1.4 Stream Generator for DocuForge AI
 */
export async function exportPdf(projectId: string): Promise<{ filename: string; buffer: Buffer }> {
  const { prisma } = await import("../db/prisma.ts");
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      documentations: {
        include: {
          sections: true,
        },
      },
    },
  });

  if (!project) {
    throw new Error(`Project '${projectId}' not found.`);
  }

  const doc = project.documentations[0];
  const lines: string[] = [];
  lines.push(`DOCUFORGE AI DOCUMENTATION: ${project.name.toUpperCase()}`);
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push(`Version: ${project.docVersion || "1.0.0"}`);
  lines.push("--------------------------------------------------");
  lines.push("");

  if (!doc || doc.sections.length === 0) {
    lines.push("No technical documentation sections generated yet.");
  } else {
    const sortedSections = doc.sections.sort((a, b) => a.order - b.order);
    for (const sec of sortedSections) {
      lines.push(`=== ${sec.title.toUpperCase()} ===`);
      lines.push("");
      const sanitizedContent = sanitizeText(sec.content);
      const plainText = sanitizedContent
        .replace(/#+\s+/g, "")
        .replace(/\*\*/g, "")
        .replace(/`/g, "")
        .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");
      
      lines.push(plainText);
      lines.push("");
      lines.push("--------------------------------------------------");
      lines.push("");
    }
  }

  const fullText = lines.join("\n");
  
  // Clean ASCII characters for standard Helvetica PDF stream rendering
  const pdfEscapedText = fullText
    .replace(/[^\x00-\x7F]/g, "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");

  const textLines = pdfEscapedText.split("\n");
  const linesPerPage = 35;
  const pagesCount = Math.ceil(textLines.length / linesPerPage) || 1;

  const pdfObjects: string[] = [];
  const pageObjectIds: number[] = [];

  pdfObjects.push(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj`);
  pdfObjects.push(`4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj`);

  let nextObjId = 5;
  for (let i = 0; i < pagesCount; i++) {
    const pageObjId = nextObjId++;
    const contentObjId = nextObjId++;
    pageObjectIds.push(pageObjId);

    const pageLines = textLines.slice(i * linesPerPage, (i + 1) * linesPerPage);
    
    let streamText = `BT\n/F1 10 Tf\n40 760 Td\n14 TL\n`;
    for (const line of pageLines) {
      streamText += `(${line}) '\n`;
    }
    streamText += `ET`;

    const streamLength = Buffer.byteLength(streamText, "utf8");

    pdfObjects.push(
      `${pageObjId} 0 obj\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 612 792] /Contents ${contentObjId} 0 R >>\nendobj`
    );

    pdfObjects.push(
      `${contentObjId} 0 obj\n<< /Length ${streamLength} >>\nstream\n${streamText}\nendstream\nendobj`
    );
  }

  const pageKids = pageObjectIds.map((id) => `${id} 0 R`).join(" ");
  pdfObjects.push(`2 0 obj\n<< /Type /Pages /Kids [${pageKids}] /Count ${pagesCount} >>\nendobj`);

  const pdfHeader = `%PDF-1.4\n`;
  let body = pdfHeader;
  const offsets: number[] = [];

  const sortedPdfObjects = pdfObjects.sort((a, b) => {
    const idA = parseInt(a.split(" ")[0]);
    const idB = parseInt(b.split(" ")[0]);
    return idA - idB;
  });

  for (const objStr of sortedPdfObjects) {
    const id = parseInt(objStr.split(" ")[0]);
    offsets[id] = Buffer.byteLength(body, "utf8");
    body += `${objStr}\n`;
  }

  const xrefOffset = Buffer.byteLength(body, "utf8");
  const maxObjId = Math.max(...Object.keys(offsets).map(Number));

  let xref = `xref\n0 ${maxObjId + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= maxObjId; i++) {
    const off = offsets[i] || 0;
    xref += `${String(off).padStart(10, "0")} 00000 n \n`;
  }

  const trailer = `trailer\n<< /Size ${maxObjId + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  const finalPdfString = body + xref + trailer;
  const pdfBuffer = Buffer.from(finalPdfString, "binary");

  return {
    filename: getSafeFilename(project.name, "pdf"),
    buffer: pdfBuffer,
  };
}
