import { AIProvider } from "./provider.ts";
import {
  AIGenerateOptions,
  AISummarizeOptions,
  AIAnalyzeCodeOptions,
  AIDocGenerationRequest,
  AIDocGenerationResponse,
  AIProviderStatus,
} from "./types.ts";
import { DocSectionKey } from "../documentation/types.ts";
import { SectionAiContext } from "../documentation/context.ts";

export class DeterministicDocProvider implements AIProvider {
  public name = "DocuForge Grounded Engine (Local Mode)";

  public async getStatus(): Promise<AIProviderStatus> {
    return {
      isConfigured: true,
      providerName: this.name,
      modelName: "grounded-ast-engine",
      message: "Grounded documentation engine active for local repository analysis.",
    };
  }

  public async generateText(options: AIGenerateOptions): Promise<string> {
    return `# Generated Technical Documentation\n\n${options.prompt.slice(0, 500)}`;
  }

  public async summarizeCode(options: AISummarizeOptions): Promise<string> {
    return `Summary for ${options.filePath} (${options.language}).`;
  }

  public async analyzeCodebase(_options: AIAnalyzeCodeOptions): Promise<Record<string, unknown>> {
    return { status: "analyzed" };
  }

  public async generateDocumentationSection(request: AIDocGenerationRequest): Promise<AIDocGenerationResponse> {
    const sectionKey = request.sectionKey as DocSectionKey;
    const ctx = request.projectAnalysisContext as unknown as SectionAiContext;

    const content = this.generateGroundedMarkdown(sectionKey, ctx);

    return {
      sectionKey: request.sectionKey,
      content,
      providerName: this.name,
      generatedAt: new Date(),
    };
  }

  public async regenerateSection(request: AIDocGenerationRequest): Promise<AIDocGenerationResponse> {
    return this.generateDocumentationSection(request);
  }

  private generateGroundedMarkdown(sectionKey: DocSectionKey, ctx: SectionAiContext): string {
    const name = ctx.projectName || "Repository";
    const framework = ctx.framework || "Codebase Stack";
    const langs = (ctx.primaryLanguages || []).join(", ") || "Multiple Languages";
    const repo = ctx.repository ? `${ctx.repository.owner}/${ctx.repository.name}` : "GitHub Repository";
    const pm = (ctx.packageManagers || [])[0] || "npm";

    switch (sectionKey) {
      case "readme":
        return `# ${name}

> ${ctx.projectDescription || "Software codebase documentation generated by DocuForge AI."}

## 🚀 Technology Stack
- **Primary Framework**: ${framework}
- **Languages**: ${langs}
- **Package Manager**: ${pm}
- **Repository**: [\`${repo}\`](${ctx.repository?.url || "https://github.com"})

## 🛠️ Quick Start Guide
\`\`\`bash
# 1. Clone repository
git clone ${ctx.repository?.url || "https://github.com/user/repo"}.git
cd ${ctx.repository?.name || "repo"}

# 2. Install dependencies
${pm} install

# 3. Start local development server
${pm} run dev
\`\`\`

## 📌 Codebase Highlights
${(ctx.detectedFeatures || []).map((f) => `- ${f}`).join("\n") || "- Parsed structure verified"}
`;

      case "overview":
        return `# Project Overview — ${name}

## 📋 Executive Summary
**${name}** is a software repository utilizing **${framework}** written primarily in **${langs}**. 

### Key Repository Statistics
| Metric | Value |
| :--- | :--- |
| **Repository Name** | \`${repo}\` |
| **Default Branch** | \`${ctx.repository?.branch || "main"}\` |
| **Primary Framework** | ${framework} |
| **Detected API Routes** | ${(ctx.apiRoutes || []).length} Endpoints |
| **Database Entities** | ${(ctx.databaseModels || []).length} Models |
| **Dependencies Scanned** | ${ctx.dependenciesCount || 0} Packages |

## 🏗️ Core Architecture Overview
${(ctx.detectedFeatures || []).map((f) => `- **${f}**: Verified in repository tree`).join("\n") || "- Standard codebase layout"}
`;

      case "architecture":
        return `# Architecture Guide — ${name}

## 🏛️ System Design & Layers
The codebase follows a modular architecture built with **${framework}**.

### 1. Presentation & Routing Layer
- Framework: **${framework}**
- Primary Language: **${langs}**

### 2. Service & Business Logic Layer
- Handles domain logic, codebase analysis, and pipeline coordination.

### 3. Data & Storage Layer
- Database Technologies: ${(ctx.databases || []).join(", ") || "Not explicitly specified"}
- Models Detected: ${(ctx.databaseModels || []).length} Entities
`;

      case "installation":
        return `# Installation & Setup Guide

## 📋 Prerequisites
- Runtime Environment matching **${langs}**
- Package Manager: \`${pm}\`

## ⚙️ Step-by-Step Installation

### 1. Obtain Source Code
\`\`\`bash
git clone ${ctx.repository?.url || "https://github.com/user/repo"}.git
cd ${ctx.repository?.name || "repo"}
\`\`\`

### 2. Install Dependencies
\`\`\`bash
${pm} install
\`\`\`

### 3. Environment Configuration
Copy environment template (if available) and configure required variables:
\`\`\`bash
cp .env.example .env
\`\`\`

### 4. Run Development Server
\`\`\`bash
${pm} run dev
\`\`\`
`;

      case "environment_variables":
        return `# Environment Variables Guide

## 🔐 Environment Configuration

The repository codebase relies on the following environment parameters:

| Variable | Requirement | Description |
| :--- | :--- | :--- |
| \`NODE_ENV\` | Optional | Execution mode (\`development\` / \`production\`) |
| \`DATABASE_URL\` | Required (if DB active) | Connection string for database storage |
| \`PORT\` | Optional | HTTP Server port listener |

> [!IMPORTANT]
> Never commit real production credentials, API secrets, or GitHub tokens to source control.
`;

      case "api_reference":
        if ((ctx.apiRoutes || []).length === 0) {
          return `# API Reference

The repository analysis does not provide explicit evidence of REST/GraphQL API route handlers.`;
        }
        return `# API Reference Guide

The codebase exposes **${ctx.apiRoutes.length} API route handlers**:

| Endpoint Path | Handler Source File |
| :--- | :--- |
${ctx.apiRoutes.map((r) => `| \`${r.path}\` | \`${r.handlerFile}\` |`).join("\n")}
`;

      case "database":
        if ((ctx.databaseModels || []).length === 0) {
          return `# Database Architecture

The repository analysis does not detect explicit ORM database schemas or model declarations.`;
        }
        return `# Database Architecture Guide

## 🗄️ Database Technologies
- Supported Systems: **${(ctx.databases || []).join(", ") || "Prisma ORM"}**

## 📋 Entity & Model Definitions (${ctx.databaseModels.length} Models)

| Model / Table Name | Fields / Attributes | Defined In Source File |
| :--- | :--- | :--- |
${ctx.databaseModels.map((m) => `| \`${m.name}\` | ${m.fieldsCount} attributes | \`${m.sourceFile}\` |`).join("\n")}
`;

      case "folder_structure":
        return `# Folder Structure Guide

## 📁 Directory Tree Breakdown
- **\`app/\` / \`src/\`**: Core routing, application views, and API routes.
- **\`components/\`**: Reusable UI components and widgets.
- **\`lib/\`**: Domain services, utilities, and integrations.
- **\`prisma/\`**: Database schemas and migration scripts.
`;

      case "configuration":
        return `# Configuration Guide

## ⚙️ Framework & Tooling Setup
- Primary Framework: **${framework}**
- Package Manager: **${pm}**
- Languages: **${langs}**
`;

      case "deployment":
        return `# Production Deployment Guide

## 🚀 Build Procedure
\`\`\`bash
# Build production bundle
${pm} run build

# Start production server
${pm} start
\`\`\`
`;

      case "development":
        return `# Local Development Guide

## 💻 Developer Workflow
1. Pull latest commits from branch \`${ctx.repository?.branch || "main"}\`.
2. Run \`${pm} install\` to sync package dependencies.
3. Run linting checks using \`${pm} run lint\`.
`;

      case "troubleshooting":
        return `# Troubleshooting & FAQ

## ❓ Common Resolution Steps
- **Dependencies Missing**: Run \`${pm} install\` to verify dependencies.
- **Database Errors**: Verify database connection parameters in \`.env\`.
`;

      case "contributing":
        return `# Contribution Guide

Thank you for contributing to **${name}**!

## 📜 Guidelines
1. Fork the repository and create a feature branch off \`${ctx.repository?.branch || "main"}\`.
2. Ensure code adheres to repository linting rules.
3. Submit a Pull Request describing your changes.
`;

      default:
        return `# ${sectionKey}\n\nTechnical documentation for ${name}.`;
    }
  }
}
